// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSs7pNvMaLk2l6bxlvR8nXU1PIQJI-0jo',
    appId: '1:1054429730741:web:b19d73e5ba1052f9752bfc',
    messagingSenderId: '1054429730741',
    projectId: 'fitnesstrackerapp-b9670',
    authDomain: 'fitnesstrackerapp-b9670.firebaseapp.com',
    storageBucket: 'fitnesstrackerapp-b9670.firebasestorage.app',
    measurementId: 'G-YRKXLRFN0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD4xxhao2s1az5cXca7EU5rlYN9ES-mdI',
    appId: '1:1054429730741:android:1c25460e3b2bd0fc752bfc',
    messagingSenderId: '1054429730741',
    projectId: 'fitnesstrackerapp-b9670',
    storageBucket: 'fitnesstrackerapp-b9670.firebasestorage.app',
  );
}
